# Pymongo helps make it easy to connect to MongoDB and perform CRUD operations.
import os
import pymongo
# The Collection class is used to access the MongoDB collection which is like a table in a relational database.
from pymongo.collection import Collection


class DataManager:
    # Initilize the QADataManager with the MongoDB URI and get a reference to the QA collection.
    def __init__(self):
        self.mongo_client = pymongo.MongoClient(os.environ["MONGO_URI"])
        self.qa_collection: Collection = self.mongo_client["cncTechnicalAi"]["qa"]

    # Method to add a QA pair to the database. It should convert the question to a vector and store it in the database to be used for vector search.
    # The answer should be stored as is for now. It may be converted to a vector later if we want to use vector search for answers as well.
    def add_qa_pair(self, question, answer):
        self.qa_collection.insert_one({"question": question, "answer": answer})

    # Method to get a QA pair from the database by its ID. The ID is generated by MongoDB when the document is inserted.
    def get_qa_pair(self, question_id):
        return self.qa_collection.find_one({"_id": question_id})

    # Method to update a QA pair in the database. Should also convert the new question to a vector to be used for vector search.
    def update_qa_pair(self, question_id, new_question, new_answer):
        self.qa_collection.update_one(
            {"_id": question_id},
            {"$set": {"question": new_question, "answer": new_answer}},
        )

    # Method to delete a QA pair from the database, it's fairly straightforward.
    def delete_qa_pair(self, question_id):
        self.qa_collection.delete_one({"_id": question_id})

    # Method to create a vector search index in the MongoDB collection
    def create_vector_search_index(
            self,
            index_name,  # The name of the index
            vector_field_name,  # The field name of the vectors
            num_dimensions,  # The number of dimensions of the vectors
            similarity,  # The similarity metric to use (e.g., "cosine", "dotProduct")
            filter_field_name=None,  # An optional field name to filter the results
    ):
        # Define the index
        index_definition = {
            "name": index_name,
            "type": "vectorSearch",  # This is a vector search index
            "fields": [
                {
                    "type": "vector",  # This field is a vector
                    "path": vector_field_name,  # The field name of the vectors
                    "numDimensions": num_dimensions,  # The number of dimensions of the vectors
                    "similarity": similarity,  # The similarity metric to use
                }
            ],
        }

        # If a filter field name is provided, add it to the index definition
        if filter_field_name:
            index_definition["fields"].append(
                {"type": "filter", "path": filter_field_name}  # This field is a filter
            )

        # Create the index in the MongoDB collection
        self.qa_collection.create_index(index_definition)

    # Method to perform a vector search in the MongoDB collection
    def vector_search(self, index_name, query_vector, filter_query=None):
        # Define the search query
        search_query = {"$vectorSearch": {"index": index_name, "query": query_vector}}

        # If a filter query is provided, add it to the search query
        if filter_query:
            search_query["$vectorSearch"]["filter"] = filter_query

        # Perform the search and return the results
        return self.qa_collection.aggregate([search_query])
